version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goingmysocial
      MYSQL_USER: social
      MYSQL_PASSWORD: mysocialpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend-api:
    build:
      context: ./monolithic  # Path to your C# API project folder
      dockerfile: Dockerfile
    container_name: goingmysocial-api
    restart: always
    depends_on:
      - mysql-db
    environment:
      ConnectionStrings__MySQLConnection: "server=mysql-db;database=goingmysocial;user=root;password=root"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5046:8080"
    networks:
      - app-network

  frontend-angular:
    build:
      context: ./web  # Path to your Angular project folder
      dockerfile: Dockerfile
    container_name: goingmysocialnetwork
    depends_on:
      - backend-api
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
